name: api_integrated_app
description: A Flutter application with API integration, animations, and enhanced UI.
publish_to: 'none'  

version: 1.0.0+1  

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP package for API integration
  http: ^0.13.6

  # State management (optional but recommended)
  provider: ^6.1.0

  # Smooth page indicator for onboarding screens
  smooth_page_indicator: ^1.1.0

  # Animations & UI enhancements
  flutter_animate: ^4.5.0
  lottie: ^2.3.2  # For animated splash screen & UI effects

  # Persistent storage (optional for caching API data)
  shared_preferences: ^2.2.2

  # Icons
  cupertino_icons: ^1.0.6

  # Navigation package (if you prefer advanced navigation)
  go_router: ^12.1.3

  # Firebase (optional - add only if needed)
  firebase_core: ^2.21.0
  firebase_auth: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/page1.png
    - assets/page2.png
    - assets/page3.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
